### ISSUE TITLE
Format address in table

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/wexplorer#12]
Put addresses into a table to improve readability
![screen shot 2015-02-10 at 9 22 18 am](https://cloud.githubusercontent.com/assets/3640800/6128737/8ce3da8a-b106-11e4-97f4-938c9dd72fc9.png)

**Comment by bsmithgall** [comment]
Are there other formatting/design changes that need to be made? Also, which is more important? This, or #10 / #11 ?

**Comment by bsmithgall** [comment]
Other things I'm thinking about:

+ Formatting the information in the contracts as a table
+ Potentially moving some way to add items to the contract instead of the company? Maybe you can add to both? I'm not totally sure how this would work.

**Comment by bsmithgall** [comment]
There's a hidden bug here too -- some companies have multiple contacts. There should be a smart way of cycling through the contacts as well.
