### ISSUE TITLE
Making fields sortable

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/wexplorer#16]
Add functionality to sort company and contract values alphabetically ![screen shot 2015-02-18 at 10 48 58 pm](https://cloud.githubusercontent.com/assets/3640800/6261628/5bc42f98-b7c0-11e4-9d5a-17c100ed4dd4.png)

**Comment by bsmithgall** [comment]
The javascript organization is also a disaster right now, so this might be a good time to think about #7 as well.
