### ISSUE TITLE
Figure out way to update data

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/wexplorer#18]
Right now the data for the app is stale (a bunch of new contracts have been added, updated, and removed). We need to figure out a plan to keep the app "fresh"

**Comment by shellicious** [comment]
- Remove line items
- Update database
- Stretch: reincorporate line items

**Comment by bsmithgall** [comment]
This ticket has actually changed tack slightly -- in an effort to promote long-term sustainability, we're looking for an in-system password-protected file upload.

Here's a screenshot of the progress so far -- I've included [wextractor](https://github.com/codeforamerica/w-drive-extractor) as a dependency to do the data processing.
