### ISSUE TITLE
List of vendors + contracts used by a specific department

### ISSUE THREAD

**Issue by shellicious** [codeforamerica/wexplorer#29]
From Debra's feedback on 5/6: the goal of this feature would quickly show a list of contracts used by her department, I&P. When she's paying a stack of invoices, she prefers to see a list of vendors (like on her paper spreadsheet), instead of looking up vendors one at a time in Wex.

Ideas for implementing:
- [ ] Use departments already associated with contracts (and consequently, vendors) from Bill/Ed's spreadsheet 
- [ ] Create lists from contracts your team is following

**Comment by hamhands** [comment]
Should we be moving wexplorer issues to pittsburgh-purchasing-suite or keep them here @bsmithgall?

**Comment by bsmithgall** [comment]
Yeah this should be moved, it's not really achievable under the current Wex backend setup.
