### ISSUE TITLE
Search bar size issues on mobile

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/wexplorer#9]
Nav searchbar isn't consistent between the search results page and the contract and vendor pages

**Comment by bsmithgall** [comment]
Screenshots plz

**Comment by hamhands** [comment]
![wexplorecap1](https://cloud.githubusercontent.com/assets/3640800/5845973/2b43ce02-a175-11e4-9137-49424dd6ec2a.gif)

**Comment by bsmithgall** [comment]
This is a problem with the table overflowing, I think. I think we should just WONTFIX this.
